// robot.js — liquid-handler worklist (generic CSV) and an Opentrons Python API v2 script.
//
// The script loads ONE plate (one replicate). Tubes hold enough volume for all
// plates, so for several plates run it once per plate with a fresh plate/tip racks.
// It has been syntax-checked, not run on hardware: always dry-run it with
// `opentrons_simulate` first.

import { PLATE_COLS, PLATE_ROWS, fmtConc } from './calc.js';
import { toCsv } from './io.js';

const well = (r, c) => `${String.fromCharCode(65 + r)}${c + 1}`;

const RACKS = {
  15: { load: 'opentrons_15_tuberack_falcon_15ml_conical', names: ['A', 'B', 'C'].flatMap((r) => [1, 2, 3, 4, 5].map((c) => `${r}${c}`)) },
  50: { load: 'opentrons_6_tuberack_falcon_50ml_conical', names: ['A1', 'A2', 'A3', 'B1', 'B2', 'B3'] },
};

/** Sources: one tube per concentration of each titrated drug, assigned to rack positions. */
export function assignTubes(plan, cfg) {
  const titrated = [plan.colRes, plan.rowRes].filter(Boolean);
  const rackType = cfg.tubeMl <= 15 ? 15 : 50;
  const spec = RACKS[rackType];
  const tubes = [];
  for (const r of titrated) {
    r.ladder?.falcons.forEach((f, i) => {
      tubes.push({
        drug: r.name,
        axis: r.axis,
        index: i,
        conc: f.concInFalcon,
        finalConc: f.finalConc,
        label: `${r.name} ${fmtConc(f.finalConc)} µg/mL final`,
      });
    });
  }
  const perRack = spec.names.length;
  tubes.forEach((t, k) => {
    t.rack = Math.floor(k / perRack);
    t.pos = spec.names[k % perRack];
  });
  return { tubes, rackType, rackCount: Math.max(1, Math.ceil(tubes.length / perRack)), load: spec.load };
}

/** One row per dispense: source tube/position → destination well, volume. */
export function worklist(plan, cfg) {
  const { tubes } = assignTubes(plan, cfg);
  const rows = [['step', 'source', 'source_rack', 'source_position', 'dest_well', 'volume_uL']];
  let step = 1;
  const nC = (plan.colRes?.series.length || 0) + 1;
  const nR = (plan.rowRes?.series.length || 0) + 1;
  for (const t of tubes) {
    for (let k = 0; k < (t.axis === 'column' ? nR : nC); k++) {
      const dest = t.axis === 'column' ? well(k, t.index) : well(t.index, k);
      rows.push([step++, t.label, t.rack + 1, t.pos, dest, +plan.volAbPerWellEach.toFixed(2)]);
    }
  }
  for (let r = 0; r < nR; r++) {
    for (let c = 0; c < nC; c++) {
      rows.push([step++, 'Inoculum', 'reservoir', 'A1', well(r, c), +plan.volBacPerWell.toFixed(2)]);
    }
  }
  return toCsv(rows);
}

function pipetteFor(maxUl) {
  if (maxUl <= 20) return { name: 'p20_single_gen2', tips: 'opentrons_96_tiprack_20ul', cap: 20 };
  if (maxUl <= 300) return { name: 'p300_single_gen2', tips: 'opentrons_96_tiprack_300ul', cap: 300 };
  return { name: 'p1000_single_gen2', tips: 'opentrons_96_tiprack_1000ul', cap: 1000 };
}

const py = (s) => JSON.stringify(String(s));

export function opentronsScript(plan, cfg) {
  const { tubes, rackCount, load } = assignTubes(plan, cfg);
  const pip = pipetteFor(Math.max(plan.volAbPerWellEach, plan.volBacPerWell));
  const nC = (plan.colRes?.series.length || 0) + 1;
  const nR = (plan.rowRes?.series.length || 0) + 1;
  const tipsNeeded = tubes.length + nC * nR; // one tip per source tube, one per inoculum well
  const tipRacks = Math.max(1, Math.ceil(tipsNeeded / 96));
  const rackSlots = [4, 5, 6, 7, 8, 9].slice(0, rackCount);
  const tipSlots = [10, 11].slice(0, tipRacks);

  const L = [];
  L.push(`# Generated by Checkerboard Assay Planner. Dry-run with opentrons_simulate before use.`);
  L.push(`# One plate per run. Not tested on hardware.`);
  L.push(`from opentrons import protocol_api`);
  L.push(``);
  L.push(`metadata = {"protocolName": "Checkerboard plate loading", "apiLevel": "2.13"}`);
  L.push(``);
  L.push(`DRUG_UL = ${+plan.volAbPerWellEach.toFixed(2)}      # per titrated drug per well`);
  L.push(`INOCULUM_UL = ${+plan.volBacPerWell.toFixed(2)}  # per well`);
  L.push(`N_COLS = ${nC}   # columns used (last one drug-free)`);
  L.push(`N_ROWS = ${nR}   # rows used (last one drug-free)`);
  L.push(``);
  L.push(`# (label, rack index, position, axis, index along the axis)`);
  L.push(`TUBES = [`);
  for (const t of tubes) L.push(`    (${py(t.label)}, ${t.rack}, ${py(t.pos)}, ${py(t.axis)}, ${t.index}),`);
  L.push(`]`);
  L.push(``);
  L.push(`def run(protocol: protocol_api.ProtocolContext):`);
  L.push(`    plate = protocol.load_labware("corning_96_wellplate_360ul_flat", 1)`);
  L.push(`    reservoir = protocol.load_labware("nest_1_reservoir_195ml", 2)`);
  L.push(`    racks = [protocol.load_labware(${py(load)}, s) for s in ${JSON.stringify(rackSlots)}]`);
  L.push(`    tips = [protocol.load_labware(${py(pip.tips)}, s) for s in ${JSON.stringify(tipSlots)}]`);
  L.push(`    pip = protocol.load_instrument(${py(pip.name)}, "right", tip_racks=tips)`);
  L.push(``);
  L.push(`    # 1) drugs: one tip per source tube, distribute along its column or row`);
  L.push(`    for label, rack, pos, axis, idx in TUBES:`);
  L.push(`        wells = (plate.columns()[idx][:N_ROWS] if axis == "column"`);
  L.push(`                 else plate.rows()[idx][:N_COLS])`);
  L.push(`        pip.distribute(DRUG_UL, racks[rack][pos], wells, new_tip="always")`);
  L.push(``);
  L.push(`    # 2) inoculum into every used well (fresh tip per well avoids drug carry-over)`);
  L.push(`    for r in range(N_ROWS):`);
  L.push(`        for c in range(N_COLS):`);
  L.push(`            pip.transfer(INOCULUM_UL, reservoir["A1"], plate.rows()[r][c],`);
  L.push(`                         new_tip="always", mix_after=(2, min(INOCULUM_UL, ${pip.cap}) * 0.5))`);
  L.push(``);
  L.push(`    protocol.comment("Cover the plate and incubate per your reference standard (CLSI M07 / ISO 20776-1).")`);
  L.push(``);
  return L.join('\n');
}
